log:
  level: debug
  format: text
  leak_sensitive_values: true # For debugging; disable in production

serve:
  proxy:
    port: 4455
    host: 0.0.0.0
  api:
    port: 4456
    host: 0.0.0.0

access_rules:
  matching_strategy: regexp
  repositories:
    - file:///etc/oathkeeper/rules.yaml

authenticators:
  oauth2_introspection:
    enabled: true
    # Keep full config here so Oathkeeper's startup validation passes.
    config:
      introspection_url: http://keycloak:8080/realms/demo/protocol/openid-connect/token/introspect
      pre_authorization:
        enabled: false
      token_from:
        header: Authorization
      introspection_request_headers:
        accept: application/jwt
        authorization: "Basic b2F0aGtlZXBlci1pbnRyb3NwZWN0b3I6S0R5MkpHZVhYNFBNTlRTUmY5REJFcmZteEI4ZFMzNFY="
      cache:
        enabled: false # debugging purposes; set to true in production
        ttl: 20s

authorizers:
  allow:
    enabled: true

mutators:
  id_token:
    enabled: false
  header:
    enabled: true
    # Keep full config here so Oathkeeper's startup validation passes.
    config:
      headers:
        Authorization: "Bearer {{ .Extra.jwt }}"

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
