name: phantom-keycloak

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: >
      start-dev
      --http-port=8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: http://localhost:8081
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
    networks:
      - phantom-net

  keycloak-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql
    networks:
      - phantom-net

volumes:
  keycloak-db-data:

networks:
  phantom-net:
    external: true
